port: 5000
baseurl: /api/v1
mysql:
  host: e6156-db.clxkc1uvbaql.us-east-1.rds.amazonaws.com
  port: 3306
  username: dbuser
  password: dbuserdbuser
  dbname: hw1
sns:
  region: us-east-2
  topicArn: arn:aws:sns:us-east-2:967961276452:ArticleNotification
aws:
  publicKey: AKIA6CXX46ASJKZKNXFC
  secretKey: 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